import Head from 'next/head'

import style from '../styles/index.module.scss'

import CustomizedTablesMarket from "../UI/Table/TableMarket";
import CustomizedTablesBasket from "../UI/Table/TableBasket";
import {useAction} from "../hooks/useAction";

const Index = () => {
  const {addBeer} = useAction()

  const dragOverHandler = (e: any) => {
    e.preventDefault()
  }

  const dragLeaveHandler = (e: any) => {
  }

  const dragStartHandler = (e: any, beer: any) => {
    console.log(beer)
  }

  const dragEndHandler = (e: any, beers: any) => {
    // addBeer(beers)
    console.log(333)
  }

  const dropHandler = (e: any) => {
    e.preventDefault()
    // addBeer(beer)
    console.log(111113123123123)
  }

  return (
    <div className={style.wrapper}>
      <Head>
        <title>Beer market</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <div className={style.wrapper_market}>
        <p className={style.wrapper_market_title}>Market</p>
        <CustomizedTablesMarket
          dragEndHandler={dragEndHandler}
          dragLeaveHandler={dragLeaveHandler}
          dragStartHandler={dragStartHandler}/>
      </div>
      <div className={style.wrapper_basket} onDrop={() => dropHandler}>
        <p className={style.wrapper_market_title}>Basket</p>
        <CustomizedTablesBasket
          dragOverHandler={dragOverHandler}
          dropHandler={dropHandler}/>
      </div>
    </div>
  )
}

export default Index
