import Head from 'next/head'

import style from '../styles/index.module.scss'

import Link from 'next/link'
import CustomizedTablesMarket from "../UI/Table/TableMarket";
import CustomizedTablesBasket from "../UI/Table/TableBasket";
import {useAction} from "../hooks/useAction";
import {useState} from "react";
import CustomizedButtons from "../UI/Button/Button";

const Index = () => {
  const {clearBasket, productBasket, productSale, productMarket} = useAction()
  const [card, setCard] = useState<any>()

  const dragLeaveHandler = (e: any) => {
    e.preventDefault()
  }

  const dragStartHandler = (e: any, product: any) => {
    setCard(product)
  }

  const dragOverHandler = (e: any) => {
    e.preventDefault()
    const products = JSON.parse(localStorage.getItem('product')!) ?? []
    const filterProduct = products.filter((item: any) => item.id !== card.id)
    productMarket(filterProduct)
    localStorage.setItem('product', JSON.stringify([...filterProduct]))
  }

  const dropHandler = (e: any) => {
    e.preventDefault()
    const selectProducts = JSON.parse(localStorage.getItem('selectProduct')!) ?? []
    localStorage.setItem('selectProduct', JSON.stringify([...selectProducts, card]))
    productBasket(card)
  }

  const salesProduct = () => {
    const selectProduct = JSON.parse(localStorage.getItem('selectProduct')!)
    const saleProduct = JSON.parse(localStorage.getItem('saleProduct')!) || []
    productSale(selectProduct)
    localStorage.setItem('saleProduct', JSON.stringify([...saleProduct, ...selectProduct]))
    localStorage.removeItem('selectProduct')
    clearBasket(null)
  }

  return (
    <div className={style.wrapper}>
      <Head>
        <title>Beer market</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <div className={style.wrapper_market}>
        <Link href='/itemsSold'>
          <CustomizedButtons
            backColorHover='#0a3d62'
            backColor='#60a3bc'
            title='Sales History'
          />
        </Link>
        <p className={style.wrapper_market_title}>Market</p>
        <CustomizedTablesMarket
          dragStartHandler={dragStartHandler}
          dragLeaveHandler={dragLeaveHandler}
        />
      </div>
      <div className={style.wrapper_basket}>
        <CustomizedButtons
          backColor='#079992'
          backColorHover='#78e08f'
          title='Sell'
          onClick={salesProduct}
        />
        <p className={style.wrapper_market_title}>Basket</p>
        <CustomizedTablesBasket
          dragOverHandler={dragOverHandler}
          dropHandler={dropHandler}
        />
      </div>
    </div>
  )
}

export default Index