import Head from 'next/head'

import style from '../styles/index.module.scss'

import CustomizedTablesMarket from "../UI/Table/TableMarket";
import CustomizedTablesBasket from "../UI/Table/TableBasket";

const Index = () => {

  const dragOverHandler = (e: any, beers: any) => {
    e.preventDefault()
  }

  const dragLeaveHandler = (e: any) => {
    console.log(1)
    e.target.style.boxShadow = 'none'
  }

  const dragStartHandler = (e: any) => {

  }

  const dragEndHandler = (e: any, beers: any) => {
  }

  const dropHandler = (e: any, beers: any) => {
    console.log(e)
    e.preventDefault()
  }

  return (
    <div className={style.wrapper}>
      <Head>
        <title>Beer market</title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <div className={style.wrapper_market}>
        <p className={style.wrapper_market_title}>Market</p>
        <CustomizedTablesMarket
          dragOverHandler={dragOverHandler}
          dragEndHandler={dragEndHandler}
          dragLeaveHandler={dragLeaveHandler}
          dragStartHandler={dragStartHandler}/>
      </div>
      <div className={style.wrapper_basket}>
        <div>
          <p className={style.wrapper_market_title}>Basket</p>
          <CustomizedTablesBasket
            dropHandler={dropHandler}/>
        </div>
      </div>
    </div>
  )
}

export default Index
